version: "3.8"

services:
  spotify:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: spotify_bot
    environment:
      - OC_PUBLIC=${OC_PUBLIC}
      - IDENTITY_PRIVATE=${IDENTITY_PRIVATE}
      - IC_HOST=${IC_HOST}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - STORAGE_INDEX_CANISTER=${STORAGE_INDEX_CANISTER}
      - PORT=5060
    ports:
      - 5060:5060
